site:
  title: My Documentation Site
  url: https://sshkodrov.github.io/docs-site/
content:
  sources:
    - url: https://github.com/sshkodrov/test1.git
      branches: ["master"] 
      start_path: /
      
    - url: https://github.com/sshkodrov/test2.git
      branches: ["master"]
      start_path: /
     
    - url: https://github.com/sshkodrov/test3.git
      branches: ["master"]
      start_path: /
     
    - url: https://github.com/sshkodrov/test4.git
      branches: ["master"]
      start_path: /
  
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
# git:
#   ensure_git_suffix: false
# runtime:
#   fetch: true
output:
  dir: ./build/site
