name: Build and Deploy Documentation Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16'

    # - name: Install dependencies
    #   run: npm install

    - name: Clone the tests repositories
      run: |
        git clone https://github.com/sshkodrov/test1.git
        git clone https://github.com/sshkodrov/test2.git
        git clone https://github.com/sshkodrov/test3.git
        git clone https://github.com/sshkodrov/test4.git
 
    # - name: Checkout test1 repository
    #   uses: actions/checkout@v4
    #   with:
    #     repository: sshkodrov/test1
    #     path: test1  

    # - name: Checkout test2 repository
    #   uses: actions/checkout@v4
    #   with:
    #     repository: sshkodrov/test2
    #     path: test2  
    # - name: Checkout test3 repository
    #   uses: actions/checkout@v4
    #   with:
    #     repository: sshkodrov/test3
    #     path: test3  

    # - name: Checkout test4 repository
    #   uses: actions/checkout@v4
    #   with:
    #     repository: sshkodrov/test4
    #     path: test4

    - name: Convert README.md to index.adoc
      run: |
        for dir in test1 test2 test3 test4; do
          if [ -d "$dir/docs" ]; then
            echo "Converting README.md to index.adoc in $dir/docs"
            # Find each README.md file and convert it to index.adoc
            find $dir/docs -name "README.md" -exec bash -c '
              input="$0"
              output="${input%/README.md}/index.adoc"
              echo "Converting $input to $output"
              pandoc "$input" -o "$output"
              # Check if the conversion worked
              if [ -f "$output" ]; then
                echo "Conversion successful: $output"
              else
                echo "Error: Conversion failed for $input"
              fi
            ' {} \;
    
            # List files in the docs directory to ensure the index.adoc exists
            echo "Listing files in $dir/docs"
            ls -l $dir/docs
          fi
        done


    - name: Build documentation with Antora
      run: |
        echo "Running Antora build..."
        npx antora playbook.yml
        echo "Checking output directory..."
        ls -l ./build
        echo "Listing contents of the build folder..."
        ls -R ./build


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.MY_ANTORA_TOKEN }}
        publish_dir: /build/site
        publish_branch: gh-pages
