name: Build and Deploy Documentation Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clone the tests repositories
      run: |
        git clone https://github.com/sshkodrov/test1.git
        # cd test1
        git clone https://github.com/sshkodrov/test2.git
        # cd test2
        git clone https://github.com/sshkodrov/test3.git
        # cd test3
        git clone https://github.com/sshkodrov/test4.git
        # cd test4

    - name: Convert README.md to index.adoc
      run: |
        for dir in test1 test2 test3 test4; do
          if [ -d "$dir/docs" ]; then
            echo "Converting README.md to index.adoc in $dir/docs"
            # Find each README.md file and convert it to index.adoc
            find $dir/docs -name "README.md" -exec bash -c '
              input="$0"
              output="${input%/README.md}/index.adoc"
              echo "Converting $input to $output"
              pandoc "$input" -o "$output"
              # Check if the conversion worked
              if [ -f "$output" ]; then
                echo "Conversion successful: $output"
              else
                echo "Error: Conversion failed for $input"
              fi
            ' {} \;
            
            echo "Listing files in $dir/docs"
            ls -l $dir/docs
          fi
        done
        
    # - name: Commit converted index.adoc back to the repository
    #   run: |
    #     for dir in test1 test2 test3 test4; do
    #       if [ -f "$dir/docs/index.adoc" ]; then
    #         cd $dir
    #         git config user.name "github-actions"
    #         git config user.email "github-actions@github.com"
            
    #         # Set the repository URL to use the GitHub token for authentication
    #         git remote set-url origin https://x-access-token:${{ secrets.MY_ANTORA_TOKEN }}@github.com/sshkodrov/${dir}.git
            
    #         git add docs/index.adoc
    #         git commit -m "Add converted index.adoc file"
    #         git push origin master  
    #       fi
    #     done



    - name: Build documentation with Antora
      run: |
        echo "Running Antora build..."
        antora --fetch playbook.yml 
        echo "Checking output directory..."
        ls -l ./build
        echo "Listing contents of the build folder..."
        ls -R ./build


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.MY_ANTORA_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
